---


    - name: cache server auth credentials
      zabbix_auth:
        login_user: Admin
        login_password: "{{ zabbix_web_admin_pass }}"
        server_url: http://localhost/zabbix

    - debug:
        var: zabbix_server_url

    - name: setup SMTP server for the default Email mediatype
      zabbix_mediatype:
        name: Email
        smtp_server: smtp.google.com
        smtp_port: 27
        from_address: "zabbix@myemailprovider.com"
        smtp_auth:
          username: my_smtp_login1
          password: my_smtp_password2

    # update zabbix.config set authentication_type=0 where authentication_type=1;
    # update users set passwd=md5('') where alias='Admin';
