---

- tags: [ zabbix, zabbix-users ]
  become: yes
  block:
    - name: "Configuring zabbix mysql server for {{ inventory_hostname }}"
      debug:
        msg: |
          #   ____     _    _    _         _      _       _
          #  |_  /__ _| |__| |__(_)_ __   /_\  __| |_ __ (_)_ _
          #   / // _` | '_ \ '_ \ \ \ /  / _ \/ _` | '  \| | ' \
          #  /___\__,_|_.__/_.__/_/_\_\ /_/ \_\__,_|_|_|_|_|_||_|
          #

    - name: work-around for setting zabbix user password
      shell:
        cmd: |
          mysql zabbix -e "show tables like 'users';"
          echo '{{ zabbix_db_pass }}'
          export MYSQL_PWD='{{ zabbix_db_pass }}'

          echo "UPDATE zabbix.users set passwd=md5('{{ zabbix_web_admin_pass }}') where alias='Admin';"
          mysql zabbix << EOSQL

          UPDATE zabbix.users set passwd=md5('{{ zabbix_web_admin_pass }}') where alias='Admin';

          UPDATE zabbix.config set default_inventory_mode=1;

          EOSQL
      args:
        executable: /bin/bash
      changed_when: False

          # echo '{{ zabbix_db_user }}'
          # echo "export MYSQL_PWD='{{ zabbix_db_pass }}'"
          # echo mysql -uzabbix zabbix -e \"SHOW TABLES;\"

          # read -r -d '' MYSQL_PWD <<'EOF'
          # {{ zabbix_db_pass }}
          # EOF
          # export MYSQL_PWD

          # mysql -u'{{ zabbix_db_user }}' zabbix << EOSQL

          # UPDATE zabbix.users set passwd=md5('{{ zabbix_web_admin_pass }}') where alias='Admin';

          # EOSQL

    # - name: reset the default Guest password
    #   zabbix_user:
    #     login_user: Admin
    #     login_password: "{{ zabbix_web_admin_pass }}"
    #     server_url: http://localhost/zabbix
    #     name: "{{ zabbix_web_guest_name }}"
    #     alias: "Guest"
    #     enabled: no

    # - name: reset the default Guest password
    #   zabbix_user:
    #     login_user: Admin
    #     login_password: "{{ zabbix_web_admin_pass }}"
    #     server_url: http://localhost/zabbix
    #     name: "{{ zabbix_web_guest_name }}"
    #     alias: "Guest1"
    #     enabled: yes

    # - name: reset the default Guest password
    #   zabbix_user:
    #     login_user: Admin
    #     login_password: "{{ zabbix_web_admin_pass }}"
    #     server_url: http://localhost/zabbix
    #     name: "{{ zabbix_web_guest_name }}1gergrg"
    #     alias: "new_user1"
    #     enabled: yes
    #     passwd: 123
    #     email: "xfexxx@bccadgers.com"

    # - name: reset the default Guest password
    #   zabbix_user:
    #     login_user: Admin
    #     login_password: "{{ zabbix_web_admin_pass }}"
    #     server_url: http://localhost/zabbix
    #     name: "{{ zabbix_web_guest_name }}1gergrg"
    #     alias: "new_ffeuser1"
    #     enabled: yes
    #     passwd: 123
    #     email: "xfexxx@bccadgers.com"
