---

- tags: [ zabbix, zabbix-selinux, selinux ]
  block:

    - name: "Configuring zabbix selinux for {{ inventory_hostname }}"
      debug:
        msg: |
          #   ____     _    _    _       ___      _ _
          #  |_  /__ _| |__| |__(_)_ __ / __| ___| (_)_ _ _  ___ __
          #   / // _` | '_ \ '_ \ \ \ / \__ \/ -_) | | ' \ || \ \ /
          #  /___\__,_|_.__/_.__/_/_\_\ |___/\___|_|_|_||_\_,_/_\_\
          #

    - include_tasks: "../bootstrap/selinux/main.yml"
      vars:
        semodule_name: zabbix-server

