---

- tags: [ zabbix, mysql, zabbix-mysql ]
  become: yes
  block:

    - name: "Configuring zabbix mysql server for {{ inventory_hostname }}"
      debug:
        msg: |
          #   ____     _    _    _       __  __      ___  ___  _
          #  |_  /__ _| |__| |__(_)_ __ |  \/  |_  _/ __|/ _ \| |
          #   / // _` | '_ \ '_ \ \ \ / | |\/| | || \__ \ (_) | |__
          #  /___\__,_|_.__/_.__/_/_\_\ |_|  |_|\_, |___/\__\_\____|
          #                                     |__/

    - name: install Zabbix-server packages
      package:
        name: "{{ zabbix_packages_server_mysql }}"
      tags: [ pkgs ]

    - name: Create a zabbix database with name '{{ zabbix_db_name }}'
      mysql_db:
        name: "{{ zabbix_db_name }}"
        target: "{{ zabbix_db_host }}"
        collation: utf8_bin
        encoding: utf8
        state: present
      register: zabbix_db_created

    - name: Find the sql archive file, where the version might have changed
      find:
        paths: /usr/share/doc/
        patterns: 'create.sql.gz'
        recurse: yes
      register: found_sql_gz

    - name: create zabbix db from sqldump
      mysql_db:
        name: "{{ zabbix_db_name }}"
        state: import
        target: "{{ found_sql_gz.files[0].path }}"
      when:
        - zabbix_db_created.changed
        - "found_sql_gz.matched == 1"

    - name: assert that we found one and only one sql tar.gz file
      debug:
        msg: |
          found {{ found_sql_gz.matched }} tar dumps
              {{ found_sql_gz }}
      when:
        - "found_sql_gz.matched != 1"
        - zabbix_db_created.changed

    - mysql_user:
        name: "{{ zabbix_db_user }}"
        password: "{{ zabbix_db_pass }}"
        encrypted: no
        host: "{{ zabbix_db_host }}"
        priv: "{{ zabbix_db_name }}.*:ALL"
        state: present

    - name: create the zabbix config dir
      file:
        path: /etc/zabbix
        state: directory

    - name: create the zabbix server config file
      template:
        src: zabbix_server.conf
        dest: /etc/zabbix/zabbix_server.conf
      notify: restart zabbix-server
      tags: [ config ]

    - name: zabbix-server (mysql)
      service:
        name: "zabbix-server"
        state: started
        enabled: yes
      tags: [ service ]

    - name: set the admin password and disabled guest access
      include_tasks: subcomponents/server-users.yml
