---

  # boilerplate
- name: bootstrap enough that ansible can run most modules
  include_tasks: "bootstrap/main.yml"
  tags: [ bootstrap ]

- tags: [ zabbix ]
  become: yes
  block:

      # boilerplate
    - name: include the distro specific var task file
      include_tasks: bootstrap/distro-vars-import2.yml
      tags: always

      ## START OF MAIN TASKS SECTION ##

    - name: Show information for this installation
      debug:
        msg: |

            #   ____     _    _    _
            #  |_  /__ _| |__| |__(_)_ __
            #   / // _` | '_ \ '_ \ \ \ /
            #  /___\__,_|_.__/_.__/_/_\_\
            #
            ## Importing LimePepper Zabbix-server role

            {% if zabbix_server_components %}
            Will install
                  repo: repo/{{ ansible_pkg_mgr }}.yml

            Server Components:
            {% for zabbix_server_component in zabbix_server_components %}
                  {{ loop.index }}) {{ zabbix_server_component }}
            {% endfor %}
            {% else %}

            {% endif %}

            Server Name:          "{{ ansible_hostname }}"
            Server Fqdn:          "{{ ansible_fqdn }}"
            Inventory Hostname:   "{{ inventory_hostname }}"

            default_ipv4:         {% if ansible_default_ipv4 is defined and 'address' in ansible_default_ipv4 %}{{ ansible_default_ipv4.address }}{% else %}<undefined>{% endif %}

            Zabbix Url:           http://{% if ansible_default_ipv4 is defined and 'address' in ansible_default_ipv4 %}{{ ansible_default_ipv4.address }}{% else %}<undefined>{% endif %}/zabbix

            default ipv6:         {% if ansible_default_ipv6 is defined and 'address' in ansible_default_ipv6 %}{{ ansible_default_ipv6.address }}{% else %}<undefined>{% endif %}

    - name: install the zabbix-api pip package ansisble dependency
      pip:
        name: zabbix-api

    - name: configure Zabbix repo if any server components are requested
      include_tasks: "repo/{{ ansible_pkg_mgr }}.yml"
      when:
        - ansible_pkg_mgr is defined
        - zabbix_server_components
      tags: zabbix-repo

    - name: install any server components passed in zabbix_server_components
      include_tasks: install/main.yml
      tags: always

      ## END OF MAIN TASKS SECTION ##
    - name: "Show debugging info for node {{ inventory_hostname }}"
      debug:
        msg: |
              #   ____     _    _    _       ___         _
              #  |_  /__ _| |__| |__(_)_ __ | __|_ _  __| |
              #   / // _` | '_ \ '_ \ \ \ / | _|| ' \/ _` |
              #  /___\__,_|_.__/_.__/_/_\_\ |___|_||_\__,_|
              #

              {% if zabbix_web_admin_pass is defined %}
              zabbix_web_admin_pass: "{{zabbix_web_admin_pass}}"

              {% endif %}
