
- tags: [ zabbix, selinux ]
  become: yes
  when: ansible_os_family == 'RedHat'
  block:

  - name: install packages required for policy editing
    package:
      name:
        - checkpolicy
        # - policycoreutils-python-utils
        - policycoreutils
        - policycoreutils-python
        - selinux-policy-devel

## seems a bit roundabout, but this was this recipe I followed
# http://melikedev.com/2013/08/19/linux-selinux-semodule-compile-pp-module-from-te-file/

  - name: create the policy template
    template:
      src: selinux/selinux_policy.j2
      dest: /tmp/my-zabbix.te
      owner: root
      group: root
      mode: 0644
    register: zabbix_selinux_policy_template

  - name: create the module
    shell:
      cmd: |
        # /usr/bin/checkmodule  -m -o /tmp/my-zabbix.mod /tmp/zabbix_selinux_policy.te
        cd /tmp
        make -f /usr/share/selinux/devel/Makefile my-zabbix.pp
    when: zabbix_selinux_policy_template.changed

  # - name: return motd to registered var2
  #   command: |
  #     /usr/bin/semodule_package -m /tmp/my-zabbix.mod -o /tmp/my-zabbix.pp

  - name: install the module
    command: |
      semodule -i /tmp/my-zabbix.pp
    when: zabbix_selinux_policy_template.changed

# # http://docs.ansible.com/ansible/latest/seboolean_module.html
  - name: set seboolean httpd_can_connect_zabbix
    seboolean:
      name: httpd_can_connect_zabbix
      state: yes
      persistent: yes
