---

- tags: [ zabbix ]
  become: yes
  block:

    - tags: [ zabbix-raspberrypi ]
      become: yes
      when:
        - ansible_lsb is defined
        - "ansible_lsb.id == 'Raspbian'"
        - "ansible_machine == 'armv7l'"
      block:

        - debug:
            msg: |
              is probably raspberrypi
              {{ ansible_lsb }}
              {% if 'id' in ansible_lsb %}
              {{ ansible_lsb.id }}
              {% endif %}
              {{ ansible_machine }}


    - tags: [ zabbix-debian ]
      become: yes
      when:
        - "ansible_os_family == 'Debian'"
        - "ansible_machine == 'x86_64'"
      block:

        - debug:
            msg: |
              is probably ubuntu or debian
              {{ ansible_lsb }}
              {% if 'id' in ansible_lsb %}
              {{ ansible_lsb.id }}
              {% endif %}
              {{ ansible_machine }}

    - name: Install the zabbix repo package
      apt:
        deb: "{{ zabbix_repo_package }}"
      register: zab_package

    - name: force cache update on new repo package
      apt:
        update_cache: yes
      when: zab_package.changed
