---

- tags: [ zabbix ]
  become: yes
  block:

  - tags: [ zabbix-raspberrypi ]
    become: yes
    when:
      - ansible_lsb is defined
      - "ansible_lsb.id == 'Raspbian'"
      - "ansible_machine == 'armv7l'"
    block:

      - debug:
          msg: |
            is probably raspberrypi
            {{ ansible_lsb }}
            {{ ansible_lsb.id }}
            {{ ansible_machine }}


  - tags: [ zabbix-debian ]
    become: yes
    when:
      - "ansible_os_family == 'Debian'"
      - "ansible_machine == 'x86_64'"
    block:

      - debug:
          msg: |
            is probably ubuntu or debian
            {{ ansible_lsb }}
            {{ ansible_lsb.id }}
            {{ ansible_machine }}

  - tags: [ zabbix-debian, repo ]
    become: yes
    when:
      - "ansible_distribution == 'Ubuntu'"
      - "ansible_distribution_major_version == '18'"
    block:

      - name: Install a .deb package from the internet.
        apt:
          deb: https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+bionic_all.deb

  - tags: [ zabbix-debian, repo ]
    become: yes
    when:
      - "ansible_distribution == 'Ubuntu'"
      - "ansible_distribution_major_version == '16'"
    block:

      - name: Install the zabbix repo package
        apt:
          deb: https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+xenial_all.deb
        register: zab_package

      - name: install shim packages for Debian 9
        apt:
          update_cache: yes
        when: zab_package.changed


  - name: update
    apt:
      update_cache: yes
      cache_valid_time: 3600
